// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	payment "ppob-service/drivers/midtrans"

	mock "github.com/stretchr/testify/mock"
)

// MidtransInterface is an autogenerated mock type for the MidtransInterface type
type MidtransInterface struct {
	mock.Mock
}

// CancelPayment provides a mock function with given fields: orderID
func (_m *MidtransInterface) CancelPayment(orderID string) {
	_m.Called(orderID)
}

// CreateVirtualAccount provides a mock function with given fields: orderID, nominal, bank
func (_m *MidtransInterface) CreateVirtualAccount(orderID int, nominal int, bank string) payment.CoreAPIResponse {
	ret := _m.Called(orderID, nominal, bank)

	var r0 payment.CoreAPIResponse
	if rf, ok := ret.Get(0).(func(int, int, string) payment.CoreAPIResponse); ok {
		r0 = rf(orderID, nominal, bank)
	} else {
		r0 = ret.Get(0).(payment.CoreAPIResponse)
	}

	return r0
}

// SetupGlobalMidtransConfig provides a mock function with given fields:
func (_m *MidtransInterface) SetupGlobalMidtransConfig() {
	_m.Called()
}
